feat: Enhance update check and backup functionality, add backup.sh script, and update preferences.conf

diff --git a/convert_x265 b/convert_x265
--- a/convert_x265
+++ b/convert_x265
@@ -2,6 +2,7 @@
 
 # This script converts video files to H265 (HEVC) format or changes their container.
 SHARE_PATH="/usr/local/share/x265_convert_script"
+SHARE_PATH="$(pwd)"
 # Load environment variables and utility functions
 if [[ -f "$SHARE_PATH/preferences.conf" ]]; then
     source $SHARE_PATH/preferences.conf
@@ -24,27 +25,21 @@ else
     exit 1
 fi
 
+if [[ -f "$SHARE_PATH/backup.sh" ]]; then
+    source $SHARE_PATH/backup.sh
+else
+    echo "Error: backup.sh not found in $SHARE_PATH. Exiting..."
+    exit 1
+fi
+
 # Verify if the required files exist
-required_files=("logging.sh" "file_utils.sh" "preferences.conf")
+required_files=("logging.sh" "file_utils.sh" "preferences.conf" "backup.sh" "check_update.sh")
 for file in "${required_files[@]}"; do
     if [[ ! -f "$SHARE_PATH/$file" ]]; then
         echo "Error: Required file $file does not exist in $SHARE_PATH. Exiting..."
         exit 1
     fi
 done
-
-# Function to set log level
-set_log_level() {
-    case "$1" in
-        DEBUG|INFO|WARNING|ERROR)
-            LOG_LEVEL="$1"
-            ;;
-        *)
-            echo "Invalid log level: $1. Valid levels are DEBUG, INFO, WARNING, ERROR."
-            exit 1
-            ;;
-    esac
-}
 
 process_file() {
     local file="$1"
@@ -72,25 +67,6 @@ display_help() {
     exit 0
 }
 
-
-
-# Function to create a backup of the original file
-backup_file() {
-    local file="$1"
-    mkdir -p "$BACKUP_DIR"
-    cp "$file" "$BACKUP_DIR"
-    log "INFO" "Backup created for: $file" "$log_file"
-}
-
-# Function to delete the backup of the original file
-delete_backup() {
-    local file="$1"
-    local backup_file="$BACKUP_DIR/$(basename "$file")"
-    if [[ -f "$backup_file" ]]; then
-        rm "$backup_file"
-        log "INFO" "Backup deleted for: $file" "$log_file"
-    fi
-}
 
 # Function to check if the file has valid subtitles
 has_valid_subtitles() {
@@ -212,12 +188,6 @@ convert_to_h265_or_change_container() {
         log "INFO" "Restoring the original file from backup: $input_file" "$log_file"
         cp "$BACKUP_DIR/$(basename "$input_file")" "$input_file"
     fi
-}
-
-# Function to clean up temporary files
-cleanup_temp_files() {
-    rm -f /tmp/tmp_h265_part_*.mkv
-    log "INFO" "Temporary files deleted" "$log_file"
 }
 
 # Function to handle signals
